services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - imaginia-backend/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./imaginia-backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - imaginia-backend/.env
    command: sh -c "npm run migration:run && npm run seed && npm start"
    
    
  react:
    container_name: react
    build: ./imaginia
    volumes:
      - react-volume:/var/www/html
    depends_on: 
      - node

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react-volume:
